# Generated by Django 2.2 on 2019-09-20 18:55

import djangit.models.proxy_models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EternalDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EternalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EternalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_ManyToManyPointer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=100, null=True)),
                ('related', models.ManyToManyField(to='examples.EternalTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=100, null=True)),
                ('name', models.TextField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examples.EternalDivision')),
                ('eternal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.EternalTeam')),
                ('tags', djangit.models.proxy_models.PointerField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examples.Tag_ManyToManyPointer')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, djangit.models.proxy_models.HasManyToManyPointerFields),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=100, null=True)),
                ('name', models.TextField()),
                ('eternal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.EternalTag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, djangit.models.proxy_models.HasManyToManyPointerFields),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=100, null=True)),
                ('name', models.TextField()),
                ('tags', djangit.models.proxy_models.PointerField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examples.Tag_ManyToManyPointer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='examples.Team')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, djangit.models.proxy_models.HasManyToManyPointerFields),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=100, null=True)),
                ('name', models.TextField()),
                ('eternal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.EternalDivision')),
                ('tags', djangit.models.proxy_models.PointerField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='examples.Tag_ManyToManyPointer')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, djangit.models.proxy_models.HasManyToManyPointerFields),
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=100, null=True)),
                ('committed_at', models.DateTimeField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('message', models.TextField(default='')),
                ('adds_division', models.ManyToManyField(related_name='added_in', to='examples.Division')),
                ('adds_tag', models.ManyToManyField(related_name='added_in', to='examples.Tag')),
                ('adds_team', models.ManyToManyField(related_name='added_in', to='examples.Team')),
                ('parent_commit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_commits', to='examples.Commit')),
                ('removes_division', models.ManyToManyField(related_name='removed_in', to='examples.EternalDivision')),
                ('removes_tag', models.ManyToManyField(related_name='removed_in', to='examples.EternalTag')),
                ('removes_team', models.ManyToManyField(related_name='removed_in', to='examples.EternalTeam')),
            ],
            options={
                'ordering': ['committed_at'],
                'abstract': False,
            },
        ),
    ]
